kind: Deployment
apiVersion: apps/v1
metadata:
  name: writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      name: writer
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: wojcio/writer
        ports:
        - containerPort: 80